#!/bin/bash

source "$( pwd )/config.sh"

[ -z $1 ] && {
    echo "
        Rename a postgres database to another.
        
        Usage: pgl_rename [SOURCE DB] [DESTINATION DB]
    "
    exit 
}

SRC=$1
DST=$2

PGPASSWORD=$OPENERP_PASS psql -h $OPENERP_HOST -U $OPENERP_USER -w -d postgres  <<EOF

/* Kill all processes */

SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '$SRC' AND pid <> pg_backend_pid();

/* Clone  */
CREATE DATABASE $DST WITH TEMPLATE $SRC  OWNER $OPENERP_USER;

/* Drop */
DROP DATABASE $SRC;  

EOF
